services:
  silverbullet:
    image: zefhemel/silverbullet:v2
    container_name: silverbullet
    restart: unless-stopped
    volumes:
      - ./space:/space
    ports:
      - "3030:3000"
    environment:
      - SB_USERNAME=chiyonn
      - SB_PASSWORD=$$HOME5519s

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    volumes:
      - ./space:/data
      - ./syncthing-config:/var/syncthing
    environment:
      - PUID=1000
      - PGID=1000

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

networks:
  default:
    driver: bridge

