services:
  silverbullet:
    image: zefhemel/silverbullet
    container_name: silverbullet
    restart: unless-stopped
    volumes:
      - ./space:/space
    ports:
      - "3030:3000"
    environment:
      - SB_USERNAME=chiyonn
      - SB_PASSWORD=$$HOME5519s
